#!/bin/bash

# Shell environment

# Default umask (rwXr-X--X)
umask 026

# Add ~/bin to $PATH
export PATH="$HOME/bin:./node_modules/.bin/:$PATH"

# Default programs and program options
export EDITOR=vim
export PAGER='less -R'

# XDG directories
export XDG_CONFIG_HOME="/home/madx/.config"
export XDG_DATA_HOME="/home/madx/.local/share"
export XDG_DATA_DIRS="/usr/local/share:/usr/share:$XDG_DATA_HOME"
export XDG_CACHE_HOME="/home/madx/.cache"

# Manpages colors
export LESS_TERMCAP_mb=$(tput bold; tput setaf 2)
export LESS_TERMCAP_md=$(tput bold)
export LESS_TERMCAP_me=$(tput sgr0)
export LESS_TERMCAP_so=$(tput bold; tput rev)
export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
export LESS_TERMCAP_us=$(tput setaf 4; tput bold)
export LESS_TERMCAP_ue=$(tput sgr0)
export LESS_TERMCAP_mr=$(tput rev)
export LESS_TERMCAP_mh=$(tput dim)
export LESS_TERMCAP_ZN=$(tput ssubm)
export LESS_TERMCAP_ZV=$(tput rsubm)
export LESS_TERMCAP_ZO=$(tput ssupm)
export LESS_TERMCAP_ZW=$(tput rsupm)

# Use NVM
. ~/.nvm/nvm.sh

# Activate vte.sh features
. /etc/profile.d/vte.sh
