#!/bin/bash

# Ne rien faire s'il n'est pas lancé de façon interactive
[ -z "$PS1" ] && return

. ~/.config/bash/environment

# Désactiver les doublons dans l'historique
export HISTCONTROL=erasedups
export HISTSIZE=2000
# Avoir un historique homogène même avec plusieurs terminaux
shopt -s histappend
export PROMPT_COMMAND='history -a'

# Couleur du prompt
PC=31

# Ajouter les binaires personnalisés
if [ -d ~/bin ]; then
  export PATH=$PATH:$HOME/bin
fi

# Importer le fichier ~/.bashrc_local
if [ -f ~/.bashrc_local ]; then
  . ~/.bashrc_local
fi

# Vérifier la taille de la fenêtre après chaque commande et, si nécessaire,
# mettre a jour les valeurs les LINES et COLUMNS
shopt -s checkwinsize

# Rendre less plus agréable pour les entrées non textuelles
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# Lire le fichier .bash_aliases pour rajouter les alias
if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

# Ajouter la complétion programmable
if [ -r /usr/share/bash-completion/bash_completion ]; then
  . /usr/share/bash-completion/bash_completion
fi
if [ -f $HOME/.bash_completion ]; then
  . $HOME/.bash_completion
fi

# Ajouter le support de la couleur à la commande ls, + quelques alias utiles
if [ "$TERM" != "dumb" ]; then
  eval "`dircolors -b`"
  alias ls='ls --color=auto'
  alias dir='ls --format=vertical'
  alias la='ls -Al'
fi

# Changer le titre de la fenêtre
case "$TERM" in
xterm*|rxvt*)
  PROMPT_COMMAND='echo -ne "\033]0;Terminal: ${PWD/$HOME/~}\007"'
  ;;
*)
  ;;
esac

export PS1='\[\e[${PC}m\]\W\[\e[0m\] $ '

# Activer le prompt personnalisé si disponible
if [ -f ~/.prompt ]; then
  . ~/.prompt
fi

