#!/bin/bash

export BASH_CONF_DIR=~/.config/bash/

. $BASH_CONF_DIR/environment

# Désactiver les doublons dans l'historique
export HISTCONTROL=erasedups
export HISTSIZE=2000
# Avoir un historique homogène même avec plusieurs terminaux
shopt -s histappend
export PROMPT_COMMAND='history -a'

# Ajouter les binaires personnalisés
if [ -d ~/bin ]; then
  export PATH=$HOME/bin:$HOME/.local/bin:$PATH
fi

# Importer le fichier ~/.bashrc_local
if [ -f $BASH_CONF_DIR/bashrc.local ]; then
  . $BASH_CONF_DIR/bashrc.local
fi

# Vérifier la taille de la fenêtre après chaque commande et, si nécessaire,
# mettre a jour les valeurs les LINES et COLUMNS
shopt -s checkwinsize

# Rendre less plus agréable pour les entrées non textuelles
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# Lire le fichier .bash_aliases pour rajouter les alias
if [ -f $BASH_CONF_DIR/aliases ]; then
  . $BASH_CONF_DIR/aliases
fi

# Ajouter la complétion programmable
if [ -r /usr/share/bash-completion/bash_completion ]; then
  . /usr/share/bash-completion/bash_completion
fi

if [ -f $BASH_CONF_DIR/completion ]; then
  . $BASH_CONF_DIR/completion
fi

# Ajouter le support de la couleur à la commande ls, + quelques alias utiles
if [ "$TERM" != "dumb" ]; then
  eval "`TERM=xterm-256color dircolors -b`"
  alias ls='ls --color=auto'
  alias dir='ls --format=vertical'
  alias la='ls -Al'
fi

export PS1='\[\e[${PC}m\]\W\[\e[0m\] $ '

# Activer le prompt personnalisé si disponible
if [ -f $BASH_CONF_DIR/prompt ]; then
  . $BASH_CONF_DIR/prompt
fi

if [ -f ~/.cache/last_working_directory ]; then
  cd "$(cat ~/.cache/last_working_directory)"
fi

