#!/bin/bash

function __prompt_git_dirty {
  git diff --quiet 2>/dev/null || echo -e "*"
}

function __prompt_git_sha1 {
  sha1="$(git log --no-color -1 --pretty=format:%h 2>/dev/null)"
  if [ $? = 0 ]; then echo "$sha1"; fi
}

function __prompt_git_branch {
  str="$(/usr/lib/git-core/git-symbolic-ref HEAD 2>/dev/null)"
  if [ $? = 0 ]; then
    echo " ${str#refs/heads/}$(__prompt_git_dirty):$(__prompt_git_sha1)"
  fi
}

function __prompt_git_wd {
  gitdir="$(git rev-parse --git-dir 2>/dev/null)"

  if [ $? = 0 ]; then
    if [ "$(git config --get core.bare)" = "true" ]; then
      echo "$(basename "$(pwd)")"
    else
      if [ "$gitdir" = ".git" ]; then
        echo "$(basename "$PWD")"
      elif [ "$gitdir" = "." ]; then
        dir=$PWD
        while [ "$(basename $dir)" != ".git" ]; do
          dir=$(dirname $dir)
        done
        echo "$(basename $(dirname "$dir")) ${PWD#$(dirname "$dir")/}"
      else
        echo "${PWD#$(dirname $(dirname "$gitdir"))/}"
      fi
    fi
  else
    pwd | sed "s/\/home\//\~/"
  fi
}

function __prompt_docker_id {
  if [ -f /.dockerenv ]; then
    echo "[$(hostname)] "
  fi
}

function __prompt_venv {
  if [ x != "x$VIRTUAL_ENV" ]; then
    echo " 🐍"
  fi
}

function __printbar {
  eval printf '%.0s$2' {1..$1}
}

function __hbar {
  __printbar $(tput cols) " "
}

function _save_wd {
  pwd > ~/.cache/last_working_directory
}

function _save_venv {
  if [ -n "$VIRTUAL_ENV" ]; then
    echo "$VIRTUAL_ENV" > ~/.cache/last_venv
  else
    rm -f ~/.cache/last_venv
  fi
}

export PS1='\[\e[G\e[0;30m\]$(__hbar)\[\e[0m\]\r$(__prompt_docker_id)\[\e[1;${PC}m\]$(__prompt_git_wd)\[\e[0m\]$(__prompt_git_branch)\[\e[0;32m\]$(__prompt_venv)\[\e[0m\]`if [ "$__RET" -ne "0" ]; then echo " \e[41;30m $__RET \e[0m"; fi` \n↳ '

case "$TERM" in
xterm*|rxvt*|screen*|st*|alacritty*)
  PROMPT_COMMAND='__RET=$?;_COLS=`tput cols`;_save_wd;_save_venv;echo -ne "\033]0;$USER@$HOSTNAME: $(__prompt_docker_id)$(__prompt_git_wd)$(__prompt_git_branch)\007";history -a'
  ;;
*)
  PROMPT_COMMAND='__RET=$?;history -a'
esac
